apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-es
  labels:
    app: {{ .Release.Name }}
spec:
  data:
    - secretKey: auth-token
      remoteRef:
        key: TELEPORT_JOINPASSWD
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-css
  target:
    name: teleport-secret
    template:
      metadata:
        annotations:
          meta.helm.sh/release-name: {{ .Release.Name }}
          meta.helm.sh/release-namespace: {{ .Release.Namespace }}
        labels:
          app.kubernetes.io/managed-by: Helm
      type: Opaque
