apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd-system
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: 1.8.x
    chart: cert-manager
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        replicaCount: 1
        nodeSelector:
          kubernetes.io/os: linux
        image:
          repository: quay.io/jetstack/cert-manager-controller
        extraArgs:
          - --dns01-recursive-nameservers=10.1.100.1:53
        cainjector:
          replicaCount: 1
          image:
            repository: quay.io/jetstack/cert-manager-cainjector
          nodeSelector:
            kubernetes.io/os: linux
        webhook:
          replicaCount: 1
          image:
            repository: quay.io/jetstack/cert-manager-webhook
          nodeSelector:
            kubernetes.io/os: linux
        global:
          leaderElection:
            namespace: "cert-manager"
            leaseDuration: 30s
            renewDeadline: 25s
            retryPeriod: 15s
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
