apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-server-app
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.releases.teleport.dev
    chart: teleport-cluster
    targetRevision: 9.0.4
    helm:
      releaseName: teleport
      values: |
        acme: true
        acmeEmail: r@ronaldmiranda.com.br
        acmeURI: ""

        clusterName: teleport.ronaldmiranda.com.br
        enterprise: false

        image: ronaldmiranda/teleport-arm
        imagePullPolicy: Always
        authenticationType: github
        podSecurityPolicy:
          enabled: false

        chartMode: standalone
        standalone:
          existingClaimName: ""
          volumeSize: 10Gi

        certManager:
          addCommonName: true
          enabled: true
          issuerName: teleport-issuer

  destination:
    name: teleport-oracle-cluster
    namespace: teleport-system
  syncPolicy:
    automated:
      prune: true
