apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-issuer
  annotations:
    helm.sh/hook-weight: "1"
spec:
  acme:
    email: {{ .Values.issuer.acme.cloudflare.email }}
    server: {{ .Values.issuer.acme.server }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-privkey
    solvers:
      {{- $cloudflare := .Values.issuer.acme.cloudflare }}
      {{- $solvers := .Values.issuer.acme.solvers }}
      {{- range $key, $value := $solvers }}
      - selector:
          dnsNames:
            {{- if $value.dnsNames }}
              {{- toYaml $value.dnsNames | nindent 12 }}
            {{- end }}
        dns01:
          cloudflare:
            email: {{ $cloudflare.email }}
            apiTokenSecretRef:
              name: {{ $cloudflare.clientSecretSecretRef.name }}
              key: {{ $cloudflare.clientSecretSecretRef.key }}
      {{- end }}
---
