{{ range .Values.clusters }}
{{ if .enabled }}
{{ $clusterName := .name }}
{{ with .applications }}
{{ range $key, $value := . }}
{{ range $key, $value := dict $key (merge ( get $.Values.appDefinitions $key) $value) }}
{{ if .enable }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: {{ .namespace }}
  {{- with .labels }}
  labels: {{ . | toYaml | nindent 4}}
  {{ end }}
  {{- with .annotations }}
  annotations: {{ . | toYaml | nindent 4}}
  {{ end }}
spec:
  project: {{ .project }}
  source: {{ .source | toYaml | nindent 4 }}
  destination: {{$clusterName}}
  {{- with .syncPolicy }}
  syncPolicy: {{ . | toYaml | nindent 4 }}
  {{- end }}

{{end}}
---
{{end}}
{{end}}
{{end}}
{{end}}
{{end}}

