{{ range .Values.clusters }}
{{ if .enabled }}
{{ $clusterName := .name }}
{{ with .applicationSets }}
{{ range $key, $value := . }}
{{ range $key, $value := dict $key (merge ( get $.Values.appsetsDefinitions $key) $value) }}
{{ if .enable }}

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: &templateName {{ $key }}-{{$clusterName}}
spec:
  generators:
    - git:
        repoURL: {{ .localVarRepo }}
        revision: {{ .localVarRevision }}
        files:
          - path: {{ .localVarFile }}
  template:
    metadata:
      name: *templateName
    spec:
      project: {{ .project }}
      source:
        repoURL: {{ .repoURL }}
        targetRevision: {{ .targetRevision | squote}}
        path: {{ .path | squote}}
        {{- with .chart}}
        chart: {{ . }}
        {{end}}
        {{- with .plugin }}
        plugin: {{- . | toYaml | nindent 10 }}
        {{ end }}
        {{- with .helm }}
        helm:
          releaseName: {{ .releaseName }}
          {{ with .values }}
          values: |
            {{- . | toString | nindent 12 }}
          {{ end }}
        {{- end }}
      destination:
        name: {{ $clusterName }}
        namespace: {{ .destination.namespace }}
      {{- if .syncPolicy }}
      syncPolicy: {{- toYaml .syncPolicy | nindent 8 }}
      {{- end }}

{{end}}
---
{{end}}
{{end}}
{{end}}
{{end}}
{{end}}


