{{ range $key, $value := .Values.projects }}
{{ if $value.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $key }}
  namespace: argocd-system
  {{- if $value.enabledFinalizers }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{ end }}
spec:
  description: {{ $value.description }}
  sourceRepos: {{ $value.sourceRepos | toYaml | nindent 4 }}
  destinations: {{ $value.destinations | toYaml | nindent 4 }}
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  {{- with $value.namespaceResourceBlacklist }}
  namespaceResourceBlacklist: {{ . | toYaml | nindent 4 }}
  {{ end }}
  {{- with $value.namespaceResourceWhitelist }}
  namespaceResourceWhitelist: {{ . | toYaml | nindent 4 }}
  {{ end }}
{{ end }}
{{ end }}
