extraManifests:
  - apiVersion: external-secrets.io/v1alpha1
    kind: ExternalSecret
    metadata:
      name: github-app-pem-es
    spec:
      dataFrom:
        - key: atlantis-config-json
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: azure-css
      target:
        creationPolicy: Owner
        name: &atlantis-config-secret atlantis-config-secret
        template:
          engineVersion: v2
          data:
            github_appid: "{{`{{ .github_appid }}`}}"
            github_secret: "{{`{{ .gh_webhook_secret }}`}}"
            key.pem: "{{`{{ .github_private_key_base64 | b64dec }}`}}"

atlantisUrl: http://atlantis.ronaldmiranda.com.br

vcsSecretName: *atlantis-config-secret

orgAllowlist: "github.com/ronald-s-homelab/*"

githubApp:
  foo: bar

environmentSecrets:
  - name: ATLANTIS_GH_APP_ID
    secretKeyRef:
      name: *atlantis-config-secret
      key: github_appid

test:
  enabled: false

# image:
#   repository: flaconi/atlantis-terragrunt
#   tag: 0.19.7-1.2.6-0.38.6-0.10.1

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: atlantis.ronaldmiranda.com.br
      paths:
        - "/"
  tls:
    - secretName: ronaldmiranda-tls
      hosts:
        - atlantis.ronaldmiranda.com.br
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

service:
  type: ClusterIP
