extraManifests:
  - apiVersion: external-secrets.io/v1alpha1
    kind: ExternalSecret
    metadata:
      name: github-app-pem-es
    spec:
      data:
        - remoteRef:
            key: github-app-pem
          secretKey: key.pem
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: azure-css
      target:
        creationPolicy: Owner
        name: github-app-pem
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: self-atlantis-in-cluster
    spec:
      ingressClassName: nginx
      # tls:
      #   - hosts:
      #       - atlantis.ronaldmiranda.com.br
      #     secretName: ronaldmiranda-cert
      rules:
        - host: atlantis.ronaldmiranda.com.br
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: self-atlantis-in-cluster
                    port:
                      number: 80

atlantisUrl: atlantis.ronaldmiranda.com.br

vcsSecretName: github-app-pem

ingress:
  enabled: false
