extraManifests:
  - apiVersion: external-secrets.io/v1alpha1
    kind: ExternalSecret
    metadata:
      name: github-app-pem-es
    spec:
      dataFrom:
        - key: atlantis-config-json
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: azure-css
      target:
        creationPolicy: Owner
        name: &atlantis-config-secret atlantis-config-secret
        template:
          engineVersion: v2
          data:
            github_appid: "{{`{{ .github_appid }}`}}"
            github_secret: "{{`{{ .gh_webhook_secret }}`}}"
            key.pem: "{{`{{ .github_private_key_base64 | b64dec }}`}}"

atlantisUrl: http://atlantis.ronaldmiranda.com.br

vcsSecretName: *atlantis-config-secret

orgAllowlist: "github.com/ronald-s-homelab/*"

githubApp:
  foo: bar

environmentSecrets:
  - name: ATLANTIS_GH_APP_ID
    secretKeyRef:
      name: *atlantis-config-secret
      key: github_appid

test:
  enabled: false

image:
  repository: ronaldmiranda/atlantis
  tag: latest

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: atlantis.ronaldmiranda.com.br
      paths:
        - "/"
  tls:
    - secretName: ronaldmiranda-tls
      hosts:
        - atlantis.ronaldmiranda.com.br
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

service:
  type: ClusterIP

repoConfig: |
  repos:
  - id: github.com/Ronald-s-Homelab/atlantis-test
    branch: /^(?i)(develop|lc[a-zA-Z]{1,3}-(\d+))$/
    apply_requirements: [mergeable]
    delete_source_branch_on_merge: true
    pre_workflow_hooks:
      - run: terragrunt-atlantis-config generate --output atlantis.yaml --parallel
    workflow: default
    allowed_overrides: [workflow]
  workflows:
    terragrunt:
      plan:
        steps:
          - run: terragrunt plan -no-color -out $PLANFILE
      apply:
        steps:
        - run: terragrunt apply -no-color $PLANFILE
