extraManifests:
  - apiVersion: external-secrets.io/v1alpha1
    kind: ExternalSecret
    metadata:
      name: github-app-pem-es
    spec:
      data:
        - remoteRef:
            key: github-app-pem
          secretKey: key.pem
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: azure-css
      target:
        creationPolicy: Owner
        name: github-app-pem

atlantisUrl: atlantis.ronaldmiranda.com.br

vcsSecretName: github-app-pem

ingress:
  enabled: true
  hosts:
    - host: atlantis.ronaldmiranda.com.br
      paths: ["/"]
  tls: []
  labels: {}
