{{ with .Values.ClusterExternalSecrets }}
{{ range $key, $value := . }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "{{ $key }}-ces"
spec:
  externalSecretName: {{ $key }}-es
  namespaceSelector:
    matchLabels:
      cert: "true"
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: doppler-css
    target:
      name: {{ $value.targetName }}
      creationPolicy: Owner
    {{- with $value.data }}
    data:
    {{- range . }}
      - secretKey: {{ .secretKey }}
        remoteRef:
          key: {{ .remoteRefKey }}
    {{- end }}
    {{- end }}
    {{- with $value.dataFrom }}
    dataFrom:
      {{- range .secretNames }}
      - key: {{ . }}
      {{- end }}
    {{- end }}
---
{{end}}
{{end}}
