{{ with .Values.clustersecretstore }}
{{ range $key, $value := . }}
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: {{ $key }}
spec:
  provider:
    {{- with $value.provider.azurekv }}
    azurekv:
      tenantId: {{ .tenantId }}
      vaultUrl: {{ .vaultUrl }}
      authSecretRef:
        clientId:
          namespace: {{ .authSecretRef.namespace }}
          name: {{ .authSecretRef.name }}
          key: ClientID
        clientSecret:
          namespace: {{ .authSecretRef.namespace }}
          name: {{ .authSecretRef.name }}
          key: ClientSecret
    {{ end }}
{{ end }}
{{ end }}
