{{ with .Values.externalSecrets }}
{{ range $key, $value := . }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ $key }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-css
  target:
    name: {{ $value.targetName }}
    creationPolicy: Owner
  data:
  {{- range $value.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRefKey }}
  {{- end }}
---
{{end}}
{{end}}
