controller:
  kind: DaemonSet
  extraArgs:
    enable-ssl-passthrough: ""
  publishService:
    enabled: true
  configMapNamespace: nginx-system
  service:
    enabled: true
    externalTrafficPolicy: Local
  config:
    custom-http-errors: 413,502,503,504
    generate-request-id: "true"
    proxy-buffer-size: "4k"
    proxy-body-size: "50m"
    proxy-read-timeout: "10"
    client-max-body-size: "200m"
    use-forwarded-headers: "true"
    use-gzip: "false"
    enable-brotli: "true"
    brotli-types: "*"
    brotli-level: "7"
    proxy-connect-timeout: "10"
    ssl-early-data: "true"
    ssl-protocols: "TLSv1.2 TLSv1.3"
    ssl_buffer_size: "2k"
    ssl-session-cache-size: "1m"
    ssl-session-tickets: "false"
    keep-alive-requests: "1000000"
    upstream-keepalive-requests: "1000000"
    http-snippet: |
      proxy_cache_path /tmp/nginx-cache levels=1:2 keys_zone=static-cache:2m max_size=100m inactive=7d use_temp_path=off;
      proxy_cache_key $scheme$proxy_host$request_uri;
      proxy_cache_lock on;
      proxy_cache_use_stale updating;
    log-format-escape-json: "true"
    log-format-upstream: '{
      "body_bytes_sent": "$body_bytes_sent",
      "bytes_sent": "$bytes_sent",
      "http_host": "$host",
      "http_referer": "$http_referer",
      "http_user_agent": "$http_user_agent",
      "http_x_forwarded_for": "$http_x_forwarded_for",
      "http_x_forwarded_proto": "$http_x_forwarded_proto",
      "http_x_real_ip": "$http_x_real_ip",
      "kubernetes_ingress_name": "$ingress_name",
      "kubernetes_namespace": "$namespace",
      "kubernetes_service_name": "$service_name",
      "kubernetes_service_port": "$service_port",
      "proxy_protocol_addr": "$proxy_protocol_addr",
      "proxy_upstream_name": "$proxy_upstream_name",
      "remote_addr": "$remote_addr",
      "remote_user": "$remote_user",
      "request_id": "$req_id",
      "request_length": "$request_length",
      "request_method": "$request_method",
      "request_path": "$uri",
      "request_proto": "$server_protocol",
      "request_query": "$args",
      "request_time": "$request_time",
      "request_uri": "$request_uri",
      "server_name": "$server_name",
      "server_port": "$server_port",
      "ssl_cipher": "$ssl_cipher",
      "ssl_protocol": "$ssl_protocol",
      "ssl_session_id": "$ssl_session_id",
      "status": "$status",
      "time": "$time_iso8601",
      "time_local": "$time_local",
      "upstream_addr": "$upstream_addr",
      "upstream_response_length": "$upstream_response_length",
      "upstream_response_time": "$upstream_response_time",
      "upstream_status": "$upstream_status"
      }'
