apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-root
  namespace: argocd-system
spec:
  generators:
  - git:
      repoURL: https://github.com/Ronald-s-Homelab/personal-homelab.git
      revision: main
      directories:
      - path: gitops/applications/*
  template:
    metadata:
      name: '{{ printf "{{path.basename}}" }}'
    spec:
      project: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/Ronald-s-Homelab/personal-homelab.git
        targetRevision: main
        path: '{{ printf "{{path}}" }}'
      destination:
        name: in-cluster
        namespace: '{{ printf "{{path.basename}}" }}'
