appsetsDefinitions: {}

appDefinitions:
  bateponto:
    namespace: argocd-system
    project: default
    source:
      repoURL: https://github.com/ronaldmiranda/bate-ponto-bot.git
      targetRevision: v2-deploy
      path: infra/stable/foundation
      helm:
        releaseName: bateponto-bot
        valueFiles:
          - ../../deploy/foundation/dev.yaml
    destination:
      namespace: bateponto
    syncPolicy: {}

  whitelist:
    namespace: argocd-system
    project: default
    source:
      repoURL: https://github.com/ronaldmiranda/enhanced-whitelist.git
      targetRevision: infra
      path: infra/chart
      helm:
        releaseName: whitelist-bot
    destination:
      namespace: bateponto
    syncPolicy: {}

  rnld-api:
    namespace: argocd-system
    project: default
    source:
      repoURL: https://github.com/ronaldmiranda/rp-discord-renamer.git
      targetRevision: main
      path: infra/charts
      helm:
        releaseName: atualizanickname
    destination:
      namespace: bateponto
    syncPolicy: {}

  # external-secrets:
  #   namespace: argocd-system
  #   project: default
  #   source:
  #     repoURL: https://charts.external-secrets.io
  #     chart: external-secrets
  #     targetRevision: v0.4.4
  #     helm:
  #       releaseName: external-secrets
  #       values: |
  #         replicaCount: 1
  #         installCRDs: true
  #         leaderElect: true
  #         resources:
  #           requests:
  #             cpu: 100m
  #             memory: 320Mi
  #           limits:
  #             cpu: 100m
  #             memory: 320Mi
  #         podLabels:
  #           app: external-secrets
  #   destination:
  #     namespace: external-secrets-system
  #   syncPolicy:
  #     automated:
  #       prune: true
  #     syncOptions:
  #       - CreateNamespace=true
