appsetsDefinitions: {}

appDefinitions:
  kube-oidc-proxy:
    namespace: argocd-system
    project: default
    source:
      repoURL: https://github.com/Ronald-s-Homelab/personal-homelab.git
      targetRevision: main
      path: gitops/stable/kube-oidc-proxy
      helm:
        releaseName: kube-oidc-proxy
        valueFiles:
          - ../../deploy/kube-oidc-proxy/values.yaml
    destination:
      namespace: openunison
    syncPolicy: {}

  bateponto:
    namespace: argocd-system
    project: default
    source:
      repoURL: https://github.com/ronaldmiranda/bate-ponto-bot.git
      targetRevision: v2-deploy
      path: infra/stable/foundation
      helm:
        releaseName: bateponto-bot
        valueFiles:
          - ../../deploy/foundation/dev.yaml
    destination:
      namespace: bateponto
    syncPolicy: {}

  whitelist:
    namespace: argocd-system
    project: default
    source:
      repoURL: https://github.com/ronaldmiranda/enhanced-whitelist.git
      targetRevision: infra
      path: infra/infra/chart
      helm:
        releaseName: whitelist-bot
    destination:
      namespace: bateponto
    syncPolicy: {}

  # external-secrets:
  #   namespace: argocd-system
  #   project: default
  #   source:
  #     repoURL: https://charts.external-secrets.io
  #     chart: external-secrets
  #     targetRevision: v0.4.4
  #     helm:
  #       releaseName: external-secrets
  #       values: |
  #         replicaCount: 1
  #         installCRDs: true
  #         leaderElect: true
  #         resources:
  #           requests:
  #             cpu: 100m
  #             memory: 320Mi
  #           limits:
  #             cpu: 100m
  #             memory: 320Mi
  #         podLabels:
  #           app: external-secrets
  #   destination:
  #     namespace: external-secrets-system
  #   syncPolicy:
  #     automated:
  #       prune: true
  #     syncOptions:
  #       - CreateNamespace=true
