applications:
  cert-manager-certs:
    enabled: true
    namespace: argo-system
    project: home-k8s
    source:
      repoURL: https://github.com/Ronald-s-Homelab/personal-homelab.git
      targetRevision: main
      chart: cert-manager-certs
      path: gitops/stable/cert-manager-certs
      helm:
        releaseName: cert-manager-certs
        values: |
          certificate:
            commonName: "*.ronaldmiranda.com.br"
            secretName: ronaldmiranda-cert
          issuer:
            acme:
              server: https://acme-v02.api.letsencrypt.org/directory
              cloudflare:
                email: r@ronaldmiranda.com.br
                clientSecretSecretRef:
                  name: cloudflare-api-token
                  key: api-token
              solvers:
                - hostedZoneName: ronaldmiranda.com.br
                  dnsNames:
                    - "ronaldmiranda.com.br"
                    - "*.ronaldmiranda.com.br"
    destination:
      server: https://kubernetes.default.svc
      namespace: cert-manager
    syncPolicy:
      automated:
        prune: true
