applications:
  common-resources-app:
    enabled: true
    namespace: argocd-system
    project: default
    source:
      repoURL: https://github.com/Ronald-s-Homelab/personal-homelab.git
      targetRevision: main
      path: gitops/stable/common
      helm:
        releaseName: common-resources
        valueFiles:
          - ../../deploy/common/values.yaml
    destination:
      name: in-cluster
      namespace: cert-manager
    syncPolicy:
      automated:
        prune: true

  teleport-application:
    enabled: true
    namespace: argocd-system
    project: default
    source:
      repoURL: https://github.com/Ronald-s-Homelab/personal-homelab.git
      targetRevision: main
      path: gitops/stable/teleport-agent
      helm:
        releaseName: teleport-agent
    destination:
      name: in-cluster
      namespace: teleport-system
    syncPolicy:
      automated:
        prune: true
      syncOptions:
        - CreateNamespace=true

applicationsets:
  self-argocd:
    localVarRepo: https://github.com/Ronald-s-Homelab/personal-homelab.git
    localVarRevision: main
    localVarFile: gitops/deploy/argocd/version

    project: home-k8s
    repoURL: https://github.com/Ronald-s-Homelab/personal-homelab.git
    targetRevision: main
    path: gitops/deploy/argocd
    plugin:
      name: helm-resolver
      env:
        - name: REPO
          value: "{{chart_repo}}"
        - name: REPO_NAME
          value: "{{chart_name}}"
        - name: CHART_NAME
          value: "{{chart_name}}"
        - name: CHART_VERSION
          value: "{{version}}"
        - name: VALUE_FILES
          value: "./values.yaml,./values.rbac.yaml"
    destination:
      name: in-cluster
      namespace: argocd-system
