clusters:
  - name: in-cluster
    enabled: true
    applicationSets: {}
    applications:
      kube-oidc-proxy:
        enable: true
      bateponto:
        enable: true
      whitelist:
        enable: true
