clusters:
  - name: in-cluster
    enabled: true
    applicationSets:
      self-argocd:
        enable: true
    applications:
      common-resources-app:
        enable: true
      nginx-ingress:
        enable: true
  - name: oracle
    enabled: true
    applicationSets:
      self-atlantis:
        enable: true
    applications:
      teleport-server-app:
        enable: true
