clusters:
  - name: in-cluster
    enabled: true
    applicationSets: {}
    applications:
      bateponto:
        enable: true
      whitelist:
        enable: true
      rnld-api:
        enable: true