clusters:
  - name: in-cluster
    enabled: true
    applicationSets: {}
    applications:
      nginx-ingress:
        enable: true
      bateponto:
        enable: true
      whitelist:
        enable: true
      rnld-api:
        enable: true
      relatorios:
        enable: true
