projects:
  home-k8s:
    enabled: true
    description: A ArgoCD Project for deploy things on homelab k8s-cluster.
    sourceRepos:
      - "*"
    destinations:
      - namespace: "*"
        name: in-cluster
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"
