FROM ubuntu:noble-20240801

LABEL maintainer=ronald

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV TZ='America/Recife'

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked --mount=type=cache,target=/var/lib/apt,sharing=locked \
  apt-get update && \
  DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends \
  sudo \
  apt-transport-https \
  bash-completion \
  ca-certificates \
  curl \
  git \
  htop \
  iproute2 \
  iptables \
  iputils-ping \
  less \
  lsb-release \
  ncat \
  socat \
  ssh \
  telnet \
  tmux \
  tree \
  unzip \
  vim \
  zsh \
  fzf \
  python3 python3-pip

# ZSH

ENV ZSH='/etc/zsh/.oh-my-zsh'
ENV ZSH_CUSTOM=$ZSH/custom

RUN bash -c \
  "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/oh-my-zsh/master/tools/install.sh)" --unattended \
  && zsh -c 'autoload -U compinit && compinit'

# Install powelevel10k theme

RUN git clone --depth=1 \
  https://github.com/romkatv/powerlevel10k.git \
  ${ZSH_CUSTOM}/themes/powerlevel10k

# Install default plugins
RUN git clone --depth=1 \
  https://github.com/zsh-users/zsh-syntax-highlighting.git \
  ${ZSH_CUSTOM}/plugins/zsh-syntax-highlighting

RUN git clone --depth=1 \
  https://github.com/zsh-users/zsh-autosuggestions \
  ${ZSH_CUSTOM}/plugins/zsh-autosuggestions

# GCloud.

RUN GCLOUD_VERSION="421.0.0" \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm" ; fi \
  && curl -o google-cloud-sdk.tar.gz -fsSL \
  "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GCLOUD_VERSION}-linux-$ARCH.tar.gz" \
  && tar -xzvf google-cloud-sdk.tar.gz -C /bin \
  && /bin/google-cloud-sdk/install.sh -q \
  && rm -f google-cloud-sdk.tar.gz \
  && unset GCLOUD_VERSION

# Docker Client.

RUN DOCKER_VERSION="23.0.1" \
  && curl -fsSL "https://download.docker.com/linux/static/stable/$(uname -m)/docker-${DOCKER_VERSION}.tgz" \
  | tar --strip-components=1 -xz -C /usr/local/bin docker/docker \
  && docker -v \
  && unset DOCKER_VERSION

RUN COMPOSE_VERSION="2.17.0" \
  && curl -fsSL -o /usr/local/bin/docker-compose \
  "https://github.com/docker/compose/releases/download/v${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" \
  && chmod +x /usr/local/bin/docker-compose \
  && docker-compose version \
  && unset COMPOSE_VERSION

# Terraform.

RUN TERRAFORM_VERSION="1.4.2" \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && curl -o terraform_linux.zip -fsSL \
  "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_$ARCH.zip" \
  && unzip terraform_linux.zip -d /bin \
  && terraform -v \
  && rm -f terraform_linux.zip \
  && unset TERRAFORM_VERSION

# yq

RUN YQ_VERSION="4.44.3" \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && curl -o /usr/local/bin/yq -fsSL \
  "https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_$ARCH" \
  && chmod +x /usr/local/bin/yq \
  && yq -V \
  && unset YQ_VERSION

# Terragrunt

RUN TERRAGRUNT_VERSION="0.45.0" \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && curl -o /bin/terragrunt -fsSL \
  "https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_$ARCH" \
  && chmod +x /bin/terragrunt \
  && terragrunt -v \
  && unset TERRAGRUNT_VERSION

# Kubectl

RUN KUBECTL_VERSION="1.29.1" \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && curl -o /bin/kubectl -fsSL \
  "https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/$ARCH/kubectl" \
  && chmod +x /bin/kubectl \
  && kubectl completion bash > /etc/profile.d/kubectl.bash.inc \
  && kubectl completion zsh > /etc/profile.d/kubectl.zsh.inc \
  && kubectl -h \
  && unset KUBECTL_VERSION

# Kubectx

RUN KUBECTX_VERSION="0.9.5" \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; fi \
  && curl -o kubectx_linux.tar.gz -fsSL \
  "https://github.com/ahmetb/kubectx/releases/download/v${KUBECTX_VERSION}/kubectx_v${KUBECTX_VERSION}_linux_$ARCH.tar.gz" \
  && tar -xzvf kubectx_linux.tar.gz -C /bin \
  && kubectx -h \
  && rm -f kubectx_linux.tar.gz \
  && unset KUBECTX_VERSION

# Kubens

RUN KUBENS_VERSION="0.9.5" \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; fi \
  && curl -o kubens_linux.tar.gz -fsSL \
  "https://github.com/ahmetb/kubectx/releases/download/v${KUBENS_VERSION}/kubens_v${KUBENS_VERSION}_linux_$ARCH.tar.gz" \
  && tar -xzvf kubens_linux.tar.gz -C /bin \
  && kubens -h \
  && rm -f kubens_linux.tar.gz \
  && unset KUBENS_VERSION

# k9s

RUN K9S_VERSION="v0.32.5" \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && TEMP_DIR="$(mktemp -d)" \
  && curl -o k9s.tar.gz -fsSLO \
  "https://github.com/derailed/k9s/releases/download/${K9S_VERSION}/k9s_Linux_$ARCH.tar.gz" \
  && tar -zxvf k9s.tar.gz -C "${TEMP_DIR}" \
  && mv ${TEMP_DIR}/k9s /usr/local/bin \
  && rm -rf k9s.tar.gz "${TEMP_DIR}" \
  && k9s version

# Helm

RUN HELM_VERSION="3.11.1" TEMP_DIR=$(mktemp -d) \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && cd $TEMP_DIR \
  && curl "https://get.helm.sh/helm-v${HELM_VERSION}-linux-$ARCH.tar.gz" | tar -zxv linux-$ARCH/helm \
  | xargs -I % mv -- % /usr/local/bin/helm \
  && helm version \
  && unset HELM_VERSION && rm -rf $TEMP_DIR

# Teleport

RUN TELEPORT_VERSION="14.3.0" TEMP_DIR=$(mktemp -d) \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && cd $TEMP_DIR \
  && curl -SL https://cdn.teleport.dev/teleport-v${TELEPORT_VERSION}-linux-$ARCH-bin.tar.gz | tar -xz --strip-components=1 \
  && mv tsh /usr/local/bin/ \
  && tsh version \
  && rm -rf $TEMP_DIR

# ArgoCD

RUN ARGO_VERSION='2.3.3' \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && curl -o /usr/local/bin/argocd -fsSL \
  "https://github.com/argoproj/argo-cd/releases/download/v${ARGO_VERSION}/argocd-linux-$ARCH" \
  && chmod +x /usr/local/bin/argocd \
  && argocd version --client

# 1Password CLI

RUN OP_VERSION='2.16.0' TEMP_DIR=$(mktemp -d) \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && cd $TEMP_DIR \
  && curl -o op.zip -fsSL \
  "https://cache.agilebits.com/dist/1P/op2/pkg/v${OP_VERSION}/op_linux_${ARCH}_v${OP_VERSION}.zip" \
  && unzip op.zip \
  && mv op /usr/bin \
  && op --version \
  && rm -rf $TEMP_DIR

RUN OP_SSH_VERSION="8.10.28" && TEMP_DIR=$(mktemp -d) \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="x64" ; fi \
  && cd $TEMP_DIR \
  && curl -SL https://downloads.1password.com/linux/tar/stable/$(uname -m)/1password-${OP_SSH_VERSION}.$ARCH.tar.gz \
  | tar -zx --strip-components=1 \
  && mv op-ssh-sign /usr/local/bin/op-ssh-sign \
  && rm -rf $TEMP_DIR

# LazyGit
RUN LG_VERSION='0.44.0' TEMP_DIR=$(mktemp -d) \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; fi \
  && cd $TEMP_DIR \
  && curl -SL \
  "https://github.com/jesseduffield/lazygit/releases/download/v${LG_VERSION}/lazygit_${LG_VERSION}_Linux_$ARCH.tar.gz" \
  | tar -zx \
  && mv lazygit /usr/local/bin/lazygit \
  && rm -rf $TEMP_DIR \
  && lazygit -h

# LazyDocker

RUN LD_VERSION='0.23.3' TEMP_DIR=$(mktemp -d) \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; fi \
  && cd $TEMP_DIR \
  && curl -SL \
  "https://github.com/jesseduffield/lazydocker/releases/download/v${LD_VERSION}/lazydocker_${LD_VERSION}_Linux_$ARCH.tar.gz" \
  | tar -zx \
  && mv lazydocker /usr/local/bin/lazydocker \
  && rm -rf $TEMP_DIR \
  && lazydocker -h

# lego
RUN LEGO_VERSION='4.18.0' TEMP_DIR=$(mktemp -d) \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && cd $TEMP_DIR \
  && curl -SL \
  "https://github.com/go-acme/lego/releases/download/v${LEGO_VERSION}/lego_v${LEGO_VERSION}_linux_$ARCH.tar.gz" \
  | tar -zx \
  && mv lego /usr/local/bin/lego \
  && rm -rf $TEMP_DIR \
  && lego -h

# doppler
RUN DOPPLER_VERSION='3.69.1' TEMP_DIR=$(mktemp -d) \
  ARCH=`uname -m`; if [[ $ARCH == "aarch64" ]] ; then ARCH="arm64" ; else ARCH="amd64" ; fi \
  && cd $TEMP_DIR \
  && curl -SL \
  "https://github.com/DopplerHQ/cli/releases/download/${DOPPLER_VERSION}/doppler_${DOPPLER_VERSION}_linux_$ARCH.tar.gz" \
  | tar -zx \
  && mv doppler /usr/local/bin/doppler \
  && rm -rf $TEMP_DIR \
  && doppler -h

COPY --from=docker/buildx-bin:0.10.4 /buildx /usr/libexec/docker/cli-plugins/docker-buildx
