kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  teleport.yaml: |
    version: v2
    proxy_listener_mode: multiplex
    teleport:
      connection_limits:
        max_connections: 100
        max_users: 5
    auth_service:
      enabled: yes
      cluster_name: teleport.ronaldmiranda.com.br
      authentication:
        second_factor: "on"
        type: github
        webauthn:
          rp_id: teleport.ronaldmiranda.com.br
      tokens:
        - 'kube:/mnt/secrets/joinpasswd'
    proxy_service:
      enabled: yes
      public_addr: 'teleport.ronaldmiranda.com.br:443'
      web_listen_addr: 0.0.0.0:443
      https_keypairs:
        - key_file: /etc/teleport-tls/tls.key
          cert_file: /etc/teleport-tls/tls.crt
    kubernetes_service:
      enabled: yes
    ssh_service:
      enabled: yes
