apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-es
  labels:
    app: {{ .Release.Name }}
spec:
  data:
    - secretKey: joinpasswd
      remoteRef:
        key: joinpasswd
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-css
  target:
    name: teleport-secret
    template:
      type: Opaque
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-cloudflare-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-css

  target:
    name: cloudflare-api-token
    creationPolicy: Owner

  data:
  - secretKey: api-token
    remoteRef:
      key: cloudflare-api-token
