apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-es
  labels:
    app: {{ .Release.Name }}
spec:
  data:
    - secretKey: joinpasswd
      remoteRef:
        key: joinpasswd
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-css
  target:
    name: teleport-secret
    template:
      type: Opaque
